// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mall/service/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)
/**
	核心功能是将具体的 URL 路径（API 端点）与相应的处理函数关联起来，并统一注册到 HTTP 服务器中。所有这些路由都受到 JWT 认证的保护
 */
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/order/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/update",
				Handler: UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/remove",
				Handler: RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/detail",
				Handler: DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/list",
				Handler: ListHandler(serverCtx),
			},
		},
		// 这组路由统一加上了 JWT 认证中间件
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
